-- Wonderland M published database schema.
-- Source SHA-256: 46217faf68f6da2befa60ee5dac21c0b9470092cafd573f668c631503951f38d
-- Generated by tools/export_database_schema.py; the source database was opened read-only.

PRAGMA foreign_keys = ON;
BEGIN;

-- table: animation_assets
CREATE TABLE animation_assets (id INTEGER PRIMARY KEY, name TEXT, sample_rate REAL, legacy INTEGER, wrap_mode TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: audio_assets
CREATE TABLE audio_assets (id INTEGER PRIMARY KEY, name TEXT, length_seconds REAL, channels INTEGER, frequency INTEGER, bits_per_sample INTEGER, load_type TEXT, compression_format TEXT, source_resource TEXT, resource_size INTEGER, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: client_versions
CREATE TABLE client_versions (
      id INTEGER PRIMARY KEY, product_name TEXT, engine TEXT, unity_version TEXT,
      il2cpp_metadata_version INTEGER, client_build TEXT, status TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT

    );

-- table: compound_recipes
CREATE TABLE compound_recipes (recipe_id TEXT PRIMARY KEY, inputs_json TEXT, outputs_json TEXT, success_rate REAL, failure_outputs_json TEXT, requirements_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: crafting_recipes
CREATE TABLE crafting_recipes (recipe_id TEXT PRIMARY KEY, workstation TEXT, tools_json TEXT, inputs_json TEXT, outputs_json TEXT, success_rate REAL, requirements_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: drop_entries
CREATE TABLE drop_entries (id INTEGER PRIMARY KEY, drop_table_id TEXT REFERENCES drop_tables(drop_table_id), drop_group_id TEXT, monster_id INTEGER REFERENCES monsters(monster_id), item_id INTEGER REFERENCES items(item_id), min_quantity INTEGER, max_quantity INTEGER, raw_probability REAL, raw_weight REAL, calculated_percentage REAL, calculation_formula TEXT, guaranteed INTEGER, conditional INTEGER, condition_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: drop_tables
CREATE TABLE drop_tables (drop_table_id TEXT PRIMARY KEY, drop_group_id TEXT, roll_type TEXT, complete_group INTEGER, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: encounter_groups
CREATE TABLE encounter_groups (encounter_group_id TEXT PRIMARY KEY, map_id INTEGER REFERENCES maps(map_id), zone_id TEXT, floor_id TEXT, region TEXT, encounter_type TEXT, formation_json TEXT, minimum_steps INTEGER, maximum_steps INTEGER, frequency REAL, encounter_weight REAL, level_min INTEGER, level_max INTEGER, restrictions_json TEXT, boundaries_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: encounter_members
CREATE TABLE encounter_members (id INTEGER PRIMARY KEY, encounter_group_id TEXT REFERENCES encounter_groups(encounter_group_id), monster_id INTEGER REFERENCES monsters(monster_id), position INTEGER, weight REAL, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: extraction_evidence
CREATE TABLE extraction_evidence (id INTEGER PRIMARY KEY, entity_type TEXT, entity_id TEXT, field_name TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: item_aliases
CREATE TABLE item_aliases (id INTEGER PRIMARY KEY, item_id INTEGER NOT NULL REFERENCES items(item_id), alias TEXT, language TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: items
CREATE TABLE items (
      item_id INTEGER PRIMARY KEY, internal_name TEXT, display_name TEXT, description TEXT,
      category TEXT, subcategory TEXT, material_type TEXT, material_rank INTEGER,
      equipment_slot TEXT, level_requirement INTEGER, stats_json TEXT, element TEXT,
      sell_price INTEGER, buy_price INTEGER, stack_size INTEGER, trade_restrictions TEXT,
      quest_item_status INTEGER, crafting_use TEXT, compound_use TEXT, icon_asset TEXT,
      
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT

    );

-- table: localization_entries
CREATE TABLE localization_entries (
      id INTEGER PRIMARY KEY, localization_key TEXT, language TEXT, display_text TEXT,
      internal_object_id TEXT, category TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
,
      UNIQUE(localization_key, language)
    );

-- table: map_connections
CREATE TABLE map_connections (id INTEGER PRIMARY KEY, source_map_id INTEGER REFERENCES maps(map_id), destination_map_id INTEGER REFERENCES maps(map_id), connection_type TEXT, source_coordinates_json TEXT, destination_coordinates_json TEXT, conditions_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: map_requirements
CREATE TABLE map_requirements (id INTEGER PRIMARY KEY, map_id INTEGER REFERENCES maps(map_id), required_quest_id INTEGER, required_flags_json TEXT, required_vehicle TEXT, required_item_id INTEGER REFERENCES items(item_id), required_level INTEGER, event_restrictions_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: maps
CREATE TABLE maps (map_id INTEGER PRIMARY KEY, internal_name TEXT, display_name TEXT, region_id TEXT REFERENCES regions(region_id), subregion TEXT, floor TEXT, dungeon TEXT, parent_map_id INTEGER REFERENCES maps(map_id), width REAL, height REAL, coordinate_system TEXT, minimap_asset TEXT, full_map_asset TEXT, tilemap_asset TEXT, scene_asset TEXT, access_requirements_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: monster_aliases
CREATE TABLE monster_aliases (id INTEGER PRIMARY KEY, monster_id INTEGER NOT NULL REFERENCES monsters(monster_id), alias TEXT, language TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: monster_locations
CREATE TABLE monster_locations (id INTEGER PRIMARY KEY, monster_id INTEGER REFERENCES monsters(monster_id), map_id INTEGER REFERENCES maps(map_id), encounter_group_id TEXT REFERENCES encounter_groups(encounter_group_id), encounter_type TEXT, floor_id TEXT, boundaries_json TEXT, afk_suitable INTEGER, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: monster_skills
CREATE TABLE monster_skills (id INTEGER PRIMARY KEY, monster_id INTEGER NOT NULL REFERENCES monsters(monster_id), skill_id TEXT, skill_name TEXT, ai_profile TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: monster_stats
CREATE TABLE monster_stats (id INTEGER PRIMARY KEY, monster_id INTEGER NOT NULL REFERENCES monsters(monster_id), hp INTEGER, sp INTEGER, atk INTEGER, def INTEGER, matk INTEGER, mdef INTEGER, spd INTEGER, resistances_json TEXT, immunities_json TEXT, weaknesses_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: monsters
CREATE TABLE monsters (
      monster_id INTEGER PRIMARY KEY, internal_name TEXT, display_name TEXT, level INTEGER,
      element TEXT, boss_status INTEGER, quest_only_status INTEGER, encounter_type TEXT,
      drop_table_id TEXT, experience_reward INTEGER, gold_reward INTEGER, model_asset TEXT,
      sprite_asset TEXT, portrait_asset TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT

    );

-- table: npc_dialogue
CREATE TABLE npc_dialogue (id INTEGER PRIMARY KEY, npc_id INTEGER REFERENCES npcs(npc_id), dialogue_id TEXT, language TEXT, dialogue_text TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: npc_functions
CREATE TABLE npc_functions (id INTEGER PRIMARY KEY, npc_id INTEGER REFERENCES npcs(npc_id), function_category TEXT, function_data_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: npc_locations
CREATE TABLE npc_locations (id INTEGER PRIMARY KEY, npc_id INTEGER REFERENCES npcs(npc_id), map_id INTEGER REFERENCES maps(map_id), raw_x REAL, raw_y REAL, x_norm REAL, y_norm REAL, direction TEXT, schedule_json TEXT, spawn_conditions_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: npcs
CREATE TABLE npcs (npc_id INTEGER PRIMARY KEY, internal_name TEXT, display_name TEXT, npc_type TEXT, dialogue_id TEXT, shop_id TEXT, conditions_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: portals
CREATE TABLE portals (portal_id TEXT PRIMARY KEY, source_map_id INTEGER REFERENCES maps(map_id), destination_map_id INTEGER REFERENCES maps(map_id), source_coordinates_json TEXT, destination_coordinates_json TEXT, conditions_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: quest_battles
CREATE TABLE quest_battles (id INTEGER PRIMARY KEY, quest_id INTEGER REFERENCES quests(quest_id), battle_id TEXT, encounter_group_id TEXT REFERENCES encounter_groups(encounter_group_id), target_monster_id INTEGER REFERENCES monsters(monster_id), kill_count INTEGER, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: quest_chains
CREATE TABLE quest_chains (id INTEGER PRIMARY KEY, quest_id INTEGER REFERENCES quests(quest_id), prerequisite_quest_id INTEGER REFERENCES quests(quest_id), followup_quest_id INTEGER REFERENCES quests(quest_id), mutually_exclusive INTEGER, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: quest_locations
CREATE TABLE quest_locations (id INTEGER PRIMARY KEY, quest_id INTEGER REFERENCES quests(quest_id), location_role TEXT, map_id INTEGER REFERENCES maps(map_id), npc_id INTEGER REFERENCES npcs(npc_id), coordinates_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: quest_requirements
CREATE TABLE quest_requirements (id INTEGER PRIMARY KEY, quest_id INTEGER REFERENCES quests(quest_id), requirement_type TEXT, target_id TEXT, quantity INTEGER, consumed INTEGER, condition_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: quest_rewards
CREATE TABLE quest_rewards (id INTEGER PRIMARY KEY, quest_id INTEGER REFERENCES quests(quest_id), reward_type TEXT, item_id INTEGER REFERENCES items(item_id), quantity INTEGER, value TEXT, selection_group TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: quest_steps
CREATE TABLE quest_steps (id INTEGER PRIMARY KEY, quest_id INTEGER REFERENCES quests(quest_id), step_order INTEGER, step_type TEXT, target_id TEXT, quantity INTEGER, data_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: quests
CREATE TABLE quests (quest_id INTEGER PRIMARY KEY, internal_name TEXT, display_title TEXT, description TEXT, category TEXT, main_quest INTEGER, side_quest INTEGER, event_quest INTEGER, repeatable INTEGER, cadence TEXT, starting_npc_id INTEGER REFERENCES npcs(npc_id), completion_npc_id INTEGER REFERENCES npcs(npc_id), completion_trigger TEXT, failure_conditions_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: regions
CREATE TABLE regions (region_id TEXT PRIMARY KEY, internal_name TEXT, display_name TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: shop_inventory
CREATE TABLE shop_inventory (id INTEGER PRIMARY KEY, shop_id TEXT REFERENCES shops(shop_id), item_id INTEGER REFERENCES items(item_id), buy_price INTEGER, sell_price INTEGER, conditions_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: shops
CREATE TABLE shops (shop_id TEXT PRIMARY KEY, shop_name TEXT, npc_id INTEGER REFERENCES npcs(npc_id), map_id INTEGER REFERENCES maps(map_id), currency TEXT, unlock_conditions_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: source_files
CREATE TABLE source_files (
      id INTEGER PRIMARY KEY, absolute_path TEXT UNIQUE, relative_path TEXT, filename TEXT,
      extension TEXT, file_size INTEGER, sha256 TEXT, detected_signature TEXT,
      readability_status TEXT, extraction_status TEXT, notes TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT

    );

-- table: teleports
CREATE TABLE teleports (teleport_id TEXT PRIMARY KEY, npc_id INTEGER REFERENCES npcs(npc_id), source_map_id INTEGER REFERENCES maps(map_id), destination_map_id INTEGER REFERENCES maps(map_id), conditions_json TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: unresolved_relationships
CREATE TABLE unresolved_relationships (id INTEGER PRIMARY KEY, relationship_type TEXT, source_id TEXT, target_id TEXT, reason TEXT, next_step TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- table: verification_issues
CREATE TABLE verification_issues (id INTEGER PRIMARY KEY, severity TEXT, issue_type TEXT, entity_type TEXT, entity_id TEXT, details TEXT, status TEXT, 
    source_file TEXT,
    source_asset_name TEXT,
    source_object_id TEXT,
    source_record_key TEXT,
    source_offset INTEGER,
    raw_value TEXT,
    parsed_value TEXT,
    extraction_method TEXT,
    confidence TEXT CHECK(confidence IN ('direct_client_record','direct_localization_match','direct_asset_relationship','strong_relationship','inferred_relationship','name_match_only','unresolved')),
    client_version TEXT,
    extraction_timestamp TEXT,
    parser_version TEXT,
    verification_status TEXT
);

-- index: idx_evidence_entity
CREATE INDEX idx_evidence_entity ON extraction_evidence(entity_type, entity_id);

-- index: idx_items_name
CREATE INDEX idx_items_name ON items(display_name);

-- index: idx_localization_text
CREATE INDEX idx_localization_text ON localization_entries(display_text);

-- index: idx_maps_name
CREATE INDEX idx_maps_name ON maps(display_name);

-- index: idx_monsters_name
CREATE INDEX idx_monsters_name ON monsters(display_name);

COMMIT;
