#!/usr/bin/env python3
"""Export the published SQLite schema without changing the database."""

from __future__ import annotations

import argparse
import hashlib
import sqlite3
from pathlib import Path


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> int:
    repository = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--database", type=Path, default=repository / "data" / "wonderland_m_complete.sqlite3")
    parser.add_argument("--output", type=Path, default=repository / "database" / "schema.sql")
    args = parser.parse_args()

    database = args.database.resolve()
    connection = sqlite3.connect(f"file:{database.as_posix()}?mode=ro", uri=True)
    try:
        rows = connection.execute(
            """
            SELECT type, name, sql
            FROM sqlite_master
            WHERE name NOT LIKE 'sqlite_%' AND sql IS NOT NULL
            ORDER BY CASE type WHEN 'table' THEN 1 WHEN 'view' THEN 2 WHEN 'index' THEN 3 ELSE 4 END, name
            """
        ).fetchall()
    finally:
        connection.close()

    lines = [
        "-- Wonderland M published database schema.",
        f"-- Source SHA-256: {sha256_file(database)}",
        "-- Generated by tools/export_database_schema.py; the source database was opened read-only.",
        "",
        "PRAGMA foreign_keys = ON;",
        "BEGIN;",
        "",
    ]
    for object_type, name, sql in rows:
        lines.extend([f"-- {object_type}: {name}", str(sql).rstrip(";") + ";", ""])
    lines.extend(["COMMIT;", ""])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Exported {len(rows)} schema objects to {args.output.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
